# Docker Compose configuration for TalentScout Hiring Assistant
version: '3.8'

services:
  hiring-assistant:
    build: .
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - APP_NAME=TalentScout Hiring Assistant
      - DEBUG=False
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    restart: unless-stopped
    
  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - hiring-assistant
    restart: unless-stopped
    profiles:
      - production
